In [1]:
import jax
import jax.numpy as jnp
import numpy as np

In [2]:
tau = 0.7
t = 10

In [74]:
jnp.ones(20)

Array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.], dtype=float32)

In [115]:
# @jax.jit
def this_function(tau, t, ones_array):
    ejemplo = jnp.where(
        jnp.cumsum(tau * ones_array)
        < tau * (lambda tau, t: jnp.floor(t / tau))(tau, t),
        tau * ones_array,
        0 * ones_array,
    )
    print(ejemplo)

    ejemplo2 = jnp.where(
        jnp.cumsum(tau * ones_array)
        <= tau * (lambda tau, t: jnp.ceil(t / tau))(tau, t),
        tau * ones_array,
        0 * ones_array,
    )
    print(ejemplo2)

    remainder = t - jnp.cumsum(ejemplo)[-1]
    return jnp.where(
        ((ejemplo2)) != ((ejemplo)),
        remainder * jnp.ones(ejemplo.shape),
        ejemplo,
    )

In [145]:
(lambda tau, t: jnp.floor(t / tau))(0.7, t)

Array(14., dtype=float32, weak_type=True)

In [146]:
t/0.7

14.285714285714286

In [142]:
ones_array  = jnp.ones(20)
tau = 0.8
t = 10

ejemplo = jnp.where(
        jnp.cumsum(tau * ones_array)
        <=  (lambda tau, t:  tau*jnp.floor(t / tau))(tau, t),
        tau * ones_array,
        0 * ones_array,
    )

print(ejemplo)


ejemplo2 = jnp.where(
        jnp.cumsum(tau * ones_array)
        <=  (lambda tau, t: tau *jnp.ceil(t / tau))(tau, t),
        tau * ones_array,
        0 * ones_array,
    )
print(ejemplo2)

remainder = t - jnp.cumsum(ejemplo2)[-1]
remainder

[0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.  0.  0.  0.  0.  0.  0.
 0.  0. ]
[0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.  0.  0.  0.  0.  0.
 0.  0. ]


Array(0.39999866, dtype=float32)

In [116]:
times_array_1 = this_function(0.7, 10, jnp.ones(20))
times_array_2 = this_function(0.8, 10, jnp.ones(20))


[0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.  0.  0.  0.
 0.  0. ]
[0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.  0.  0.
 0.  0. ]
[0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.  0.  0.  0.  0.  0.  0.
 0.  0. ]
[0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.  0.  0.  0.  0.  0.
 0.  0. ]


In [113]:
jnp.sum(times_array_2)

Array(10., dtype=float32)

In [114]:
times_array_2

Array([0.8      , 0.8      , 0.8      , 0.8      , 0.8      , 0.8      ,
       0.8      , 0.8      , 0.8      , 0.8      , 0.8      , 1.1999989,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       ], dtype=float32)

In [95]:
ham_array = jnp.array([np.random.rand(2,2) for _ in range(20)])

In [96]:
print(times_array.shape)
print(ham_array.shape)

(20,)
(20, 2, 2)


In [97]:
jnp.einsum("i, ijk-> jk", times_array, ham_array)

Array([[5.5536876, 2.849744 ],
       [5.331116 , 5.147647 ]], dtype=float32)

In [39]:
ejemplo = jnp.where(
    jnp.cumsum(tau * jnp.ones(20))
    <= tau * (lambda tau, t: jnp.floor(t / tau))(tau, t),
    tau * jnp.ones(20),
    0 * jnp.ones(20),
)
ejemplo

Array([0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7,
       0.7, 0. , 0. , 0. , 0. , 0. , 0. ], dtype=float32)

In [15]:
remainder = t - jnp.cumsum(ejemplo)[-1]
remainder

Array(0.20000172, dtype=float32)

In [40]:
ejemplo2 = jnp.where(
    jnp.cumsum(tau * jnp.ones(20))
    <= tau * (lambda tau, t: jnp.ceil(t / tau))(tau, t),
    tau * jnp.ones(20),
    0 * jnp.ones(20),
)
ejemplo2

Array([0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7,
       0.7, 0.7, 0. , 0. , 0. , 0. , 0. ], dtype=float32)

In [69]:
jnp.where(((ejemplo2)) != ((ejemplo)), remainder*jnp.ones(ejemplo.shape), ejemplo)

Array([0.7       , 0.7       , 0.7       , 0.7       , 0.7       ,
       0.7       , 0.7       , 0.7       , 0.7       , 0.7       ,
       0.7       , 0.7       , 0.7       , 0.7       , 0.20000172,
       0.        , 0.        , 0.        , 0.        , 0.        ],      dtype=float32)